### ISSUE TITLE
[BP_EP] Global option to turn all BP_EP invisible in game

### ISSUE THREAD

**Issue by matGonot** [Nikuichi/Explo#10]
It might be interesting to have a global option (i.e. not to check each BP one by one) to make all BP_EP invisible.
The player wouldn't have to find the trigger, it would force us to work on signs and calls.

**Comment by Nikuichi** [comment]
Fixed : https://github.com/Nikuichi/Explo/commit/6eb2a7e665bec9a285f70d7b36a8046293f49b79
