### ISSUE TITLE
[BP_EP] Display the wanted view to solve the puzzle in edit mode

### ISSUE THREAD

**Issue by matGonot** [Nikuichi/Explo#11]
Une option individuelle à chaque BP_EP pour faire apparaitre une camera debug a la position voulue pour résoudre le puzzle.

- La hauteur de la camera correspondrait a la hauteur de la camera joueur dans BP_FirstPersonCharacter
- L'orientation correspondrait aux valeurs rentrée dans le BP_EP

Faire apparaitre cette caméra faciliterait seulement le setup d'un puzzle, cette camera n'a pas pour but d'apparaitre en play mode.

**Comment by Nikuichi** [comment]
Fixed : https://github.com/Nikuichi/Explo/commit/28b54adb32854db50a0559b13e869e221cbbe369
