### ISSUE TITLE
Modifier l'ouverture de la salle de stockage de la darkroom

### ISSUE THREAD

**Issue by Nikuichi** [Nikuichi/Explo#12]
![image](https://github.com/Nikuichi/Explo/assets/12612621/2e739a1a-ef99-4b18-a6a6-05cbcd6eb562)

Faire en sorte que l'ouverture du mur permette de voir l'emplacement où sera l'échelle.

![image](https://github.com/Nikuichi/Explo/assets/12612621/7f87581e-2a96-4fa3-95a0-2ccff04689d9)

**Comment by CaptainNecate** [comment]
Une grande fenêtre pour les grands garcons
