### ISSUE TITLE
Objects loose physics when added to BP_EnvironmentPuzzle list

### ISSUE THREAD

**Issue by matGonot** [Nikuichi/Explo#2]
- Add objects to a "Object to add" List in BP_EnvironmentPuzzle
- Don't make them as "Actor Hidden in game"
- Try to walk on these objects
- See that you fall across/no clip

**Comment by Nikuichi** [comment]
Should be fixed with this CL https://github.com/Nikuichi/Explo/commit/f74452835f2f791fb6a1743e6c8d63279acaa4a5
