### ISSUE TITLE
Hide all objects in the ObjectToAdd list from Bp_EnvironmentPuzzle

### ISSUE THREAD

**Issue by matGonot** [Nikuichi/Explo#4]
Instead of ticking the "Hidden in game" box on each object on the list, a boolean directly on Bp_EnvironmentPuzzle could hide every objects on its list.

**Comment by Nikuichi** [comment]
Should be fixed with this CL https://github.com/Nikuichi/Explo/commit/f74452835f2f791fb6a1743e6c8d63279acaa4a5
