### ISSUE TITLE
[Bp_EnvPuzzle] Level disapears when added to "requiered level"

### ISSUE THREAD

**Issue by matGonot** [Nikuichi/Explo#9]
- Add a Puzzle Number in the "required puzzle" line of a new Bp_EnvironmentalPuzzle
- Complete this new puzzle (with the required puzzle completed)
- Observe that **the Level added in the "Level to Add" list in the "required puzzle" now disappears** after this new puzzle is completed

**Comment by matGonot** [comment]
Exemple on TestMap_LD : 
- Complete puzzle 1 (Boat)
- Complete puzzle 2 (Bridge) (which requires puzzle 1)
- Note that puzzle 1 (boat) disappears as soon as you have completed puzzle 2 (bridge).

**Comment by Nikuichi** [comment]
Fixed : https://github.com/Nikuichi/Explo/commit/924b5bdf269a6e3810f37fc4802cac104520a7cb
